services:
  postgres-main:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432" 
  temus-be:
    build: ./be/
    ports:
      - 5000:5000
  temus-fe:
    build: ./fe/ 
    ports: 
      - 8501:8501 
  temus-etl:
    build: ./etl/ 
    ports: 
     -3001:3001
volumes:
  postgres-db-volume:
  postgres_data: