services:
  postgres-main:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432" 
  temus-be:
    build: ./be/
    ports:
      - 3000:3000
    environment:
      - DB_URL=postgres-main
      - RAW_PATH=/app/raw
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres-main
    volumes:
      - ./raw:/app/raw
  temus-fe:
    build: ./fe/ 
    ports: 
      - 8501:8501 
    environment:
      - BACKEND_URL=http://host.docker.internal:3000
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - temus-be
  temus-etl:
    build: ./etl/ 
    ports: 
     - 3001:3001
    environment:
      - RAW_PATH=/app/raw
      - PYTHONUNBUFFERED=1
    volumes:
      - ./raw:/app/raw
    depends_on:
      - postgres-main
volumes:
  postgres-db-volume:
  postgres_data: